### ISSUE TITLE
需要帮助  need helper

### ISSUE THREAD

**Issue by DotnetManGoYu** [neoPix/bluelinky-stamps#2]
感谢@Hacksore 和@neoPix作者为我制作中国地区的bluelink第三方软件提供了思路。
在中国地区，appid是ed01581a-380f-48cd-83d4-ed1490c272d0，可以提供下这个代码的stamps库么，或者这种库的数据应该从哪里获取，愿作者能提供一些帮助

Thanks for @Hacksore  and  @neoPix‘s  source code 
in china ,bluelinke appid is ed01581a-380f-48cd-83d4-ed1490c272d0  ,i need this stamps library  or can you tell me how to get this library ,I hope the author can provide some help  ,thanks

**Comment by neoPix** [comment]
Hi @ad666666,

Part of the process is described here : https://github.com/Hacksore/hyundai-kia-stamp or even here for ARM : https://github.com/Hacksore/hyundai-kia-stamp/tree/arm
I also written a bit on how I extracted the data here : https://www.balandavid.com/fr/2021/08/bluelinky-laventure-de-la-signature-de-requetes.html :warning: it's in french :fr:.
Then I'll integrate to this process for regular token generation.

**Comment by neoPix** [comment]
@ad666666 did you find a way around ?

**Comment by Hacksore** [comment]
Someone needs to reverse the China app APK and extract the native bin. Hopefully, an x86 binary is shipped with the app as they are easier to work with but in my experience, it's only the ARM variant 🥴.

Next would be to follow @neoPix's [blog post](https://www.balandavid.com/posts/2021/08/bluelinky-laventure-de-la-signature-de-requetes/#nature-du-probleme) on how he has done this reverse engineering.

Once you have all that you can then add the supporting java code to the https://github.com/Hacksore/hyundai-kia-stamp project. Maintaining the original app java package structure has seemed to be important as well when invoking native methods.
