### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by fuatakgun** [neoPix/bluelinky-stamps#3]
Just wanted to thank you for this great solution. We own a home assistant integration (https://github.com/fuatakgun/kia_uvo) and had faced this issue regarding to daily changing stamps and your solution helped us to get unblocked.

we are getting latest stamps from your repository to login into servers. (https://github.com/fuatakgun/kia_uvo/blob/master/custom_components/kia_uvo/KiaUvoApiEU.py#L80)

Thanks again and much appreciated.

**Comment by neoPix** [comment]
Hi @fuatakgun,

Thanks for the feedback.
The stamp issue I faced with Bluelinky was a tough one to tackle.
I'm glad it helps others.

And congrats on the Python implementation. It looks good !

**Comment by andig** [comment]
I'd like to join the thanks from [evcc](https://evcc.io). Also big thank you for the backlink! Really great work figuring this one out...
