### ISSUE TITLE
Stamps for Hyundai Bluelink Australia

### ISSUE THREAD

**Issue by muneeb1990** [neoPix/bluelinky-stamps#6]
Hi, I'm trying to enable support for Hyundai Bluelink Australia in [this](https://github.com/Hyundai-Kia-Connect/kia_uvo/discussions/462) Home Assistant integration but it seems like the stamps are completely different from EU and US so I'm hoping you can assist with adding the support for AU. 

I've tried to follow the [guide](https://www.balandavid.com/posts/2021/08/bluelinky-laventure-de-la-signature-de-requetes/#nature-du-probleme) but I'm having some trouble finding lib*.so files. [Here's](https://anonymfile.com/RYR7B/bluelink-base.zip) the extracted zip file of the APK.

I've also been running MITM and have found the following:
ccsp-application-id: 55e32c34-6e47-4122-ad61-c74904ef975c
Stamp: Yphzo3vRdjKtSNVx4ICDzrDfrMpHivrb/Qcf6LxWuNTUWPAdDOccnI8fus7cbx8=

Please let me know if you need more information.

**Comment by muneeb1990** [comment]
Bump

**Comment by bitnimble** [comment]
Stamps for Australia are now available here: https://github.com/bitnimble/bluelinky-stamps-au

Still working on getting the actual libraries (bluelinky / hyundai-kia-connect) updated though.

**Comment by neoPix** [comment]
Hey, missed this issue.
It's now available here https://github.com/neoPix/bluelinky-stamps/blob/master/hyundai-f9ccfdac-a48d-4c57-bd32-9116963c24ed.v2.json.
Thanks @bitnimble  for the great work.

**Comment by bitnimble** [comment]
Oh neat, will close my repo then, thanks! 👌
